export const ALL_CAR_REQUEST = "ALL_CAR_REQUEST";
export const ALL_CAR_SUCCESS = "ALL_CAR_SUCCESS";
export const ALL_CAR_FAIL = "ALL_CAR_FAIL";

export const ADMIN_CAR_REQUEST = "ADMIN_CAR_REQUEST";
export const ADMIN_CAR_SUCCESS = "ADMIN_CAR_SUCCESS";
export const ADMIN_CAR_FAIL = "ADMIN_CAR_FAIL";

export const SELLER_CAR_SUCCESS = "SELLER_CAR_SUCCESS";

export const RELATED_CAR_REQUEST = "RELATED_CAR_REQUEST";
export const RELATED_CAR_SUCCESS = "RELATED_CAR_SUCCESS";
export const RELATED_CAR_FAIL = "RELATED_CAR_FAIL";

export const NEW_CAR_REQUEST = "NEW_CAR_REQUEST";
export const NEW_CAR_SUCCESS = "NEW_CAR_SUCCESS";
export const NEW_CAR_RESET = "NEW_CAR_RESET";
export const NEW_CAR_FAIL = "NEW_CAR_FAIL";

export const UPDATE_CAR_REQUEST = "UPDATE_CAR_REQUEST";
export const UPDATE_CAR_SUCCESS = "UPDATE_CAR_SUCCESS";
export const UPDATE_CAR_RESET = "UPDATE_CAR_RESET";
export const UPDATE_CAR_FAIL = "UPDATE_CAR_FAIL";

export const DELETE_CAR_REQUEST = "DELETE_CAR_REQUEST";
export const DELETE_CAR_SUCCESS = "DELETE_CAR_SUCCESS";
export const DELETE_CAR_RESET = "DELETE_CAR_RESET";
export const DELETE_CAR_FAIL = "DELETE_CAR_FAIL";

export const CAR_DETAILS_REQUEST = "CAR_DETAILS_REQUEST";
export const CAR_DETAILS_SUCCESS = "CAR_DETAILS_SUCCESS";
export const CAR_DETAILS_FAIL = "CAR_DETAILS_FAIL";

export const NEW_REVIEW_REQUEST = "NEW_REVIEW_REQUEST";
export const NEW_REVIEW_SUCCESS = "NEW_REVIEW_SUCCESS";
export const NEW_REVIEW_RESET = "NEW_REVIEW_RESET";
export const NEW_REVIEW_FAIL = "NEW_REVIEW_FAIL";

export const ALL_REVIEW_REQUEST = "ALL_REVIEW_REQUEST";
export const ALL_REVIEW_SUCCESS = "ALL_REVIEW_SUCCESS";
export const ALL_REVIEW_FAIL = "ALL_REVIEW_FAIL";

export const DELETE_REVIEW_REQUEST = "DELETE_REVIEW_REQUEST";
export const DELETE_REVIEW_SUCCESS = "DELETE_REVIEW_SUCCESS";
export const DELETE_REVIEW_RESET = "DELETE_REVIEW_RESET";
export const DELETE_REVIEW_FAIL = "DELETE_REVIEW_FAIL";

export const CLEAR_SEARCH_RESULTS = "CLEAR_SEARCH_RESULTS";

export const CLEAR_ERRORS = "CLEAR_ERRORS";