export const NEW_SUBSCRIPTION_REQUEST = "NEW_SUBSCRIPTION_REQUEST";
export const NEW_SUBSCRIPTION_SUCCESS = "NEW_SUBSCRIPTION_SUCCESS";
export const NEW_SUBSCRIPTION_RESET = "NEW_SUBSCRIPTION_RESET";
export const NEW_SUBSCRIPTION_FAIL = "NEW_SUBSCRIPTION_FAIL";

export const ALL_SUBSCRIPTIONS_REQUEST = "ALL_SUBSCRIPTIONS_REQUEST";
export const ALL_SUBSCRIPTIONS_SUCCESS = "ALL_SUBSCRIPTIONS_SUCCESS";
export const ALL_SUBSCRIPTIONS_FAIL = "ALL_SUBSCRIPTIONS_FAIL";

export const DELETE_SUBSCRIPTION_REQUEST = "DELETE_SUBSCRIPTION_REQUEST";
export const DELETE_SUBSCRIPTION_SUCCESS = "DELETE_SUBSCRIPTION_SUCCESS";
export const DELETE_SUBSCRIPTION_RESET = "DELETE_SUBSCRIPTION_RESET";
export const DELETE_SUBSCRIPTION_FAIL = "DELETE_SUBSCRIPTION_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";